repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format
        entry: ruff format
        language: system
        types: [python]
        args: [--line-length=88]

      - id: ruff-check
        name: Ruff Lint
        entry: ruff check
        language: system
        types: [python]
        args: [--fix]
        pass_filenames: false