name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_call: # Allow this workflow to be called by other workflows

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v5"

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -e ".[dev]"

      - name: "Run"
        run: python3 -m ruff check .
